#  Make WWW under unix for NeXT
#
CMN = ../../../Implementation/
LM = ../
#CFLAGS = -I$(CMN) -I$(LM) -DDEBUG
CFLAGS = -I$(CMN) -I$(LM) -Wall -g -DDEBUG -std=c89
CC = gcc
LFLAGS =

include $(LM)CommonMakefile
